name: Build and publish PHP binaries

on:
  push:
    branches: "**"
    tags-ignore: "**"
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build-linux:
    name: PM5 - PHP 8.4 Linux

    permissions:
      contents: write

    uses: ./.github/workflows/main-pm-matrix.yml
    with:
      pm-version-major: 5
      php-version-base: "8.4"
      special-release: default-latest
      pm-preview: false
    secrets: inherit

  publish-archive-release:
    name: Publish archive release
    needs: [build-linux]
    runs-on: ubuntu-24.04

    permissions:
      contents: write

    if: ${{ github.ref_name == 'stable' && github.ref_type == 'branch' && !contains(github.event.head_commit.message, '[no release]') }}

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v6
        with:
          path: ${{ github.workspace }}

      - name: Generate release notes
        run: |
          echo "Built by: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}" >> changelog.md
          echo "Build number: ${{ github.run_number }}" >> changelog.md
          echo -e "\n\n\n" >> changelog.md
          echo ":information_source: **Linux/MacOS users**: Please see [this page](https://doc.pmmp.io/en/rtfd/faq/installation/opcache.so.html) to fix extension loading errors." >> changelog.md

      - name: Create release
        uses: ncipollo/release-action@v1.20.0
        with:
          artifacts: |
            ${{ github.workspace }}/*PHP-8.4-Linux-PM5/*.tar.gz
            ${{ github.workspace }}/*PHP-8.4.gdbinit/*.gdbinit
          name: PHP 8.4 Linux PM5 (Build ${{ github.run_number }})
          tag: php-build-${{ github.run_number }}
          commit: ${{ github.sha }}
          allowUpdates: false
          bodyFile: ${{ github.workspace }}/changelog.md
